services:
    GeekCell\SodiumBundle\Sodium\Crypto\Box:
        arguments:
            - '%geek_cell_sodium.public_key%'
            - '%geek_cell_sodium.private_key%'
        tags:
            - { name: 'geek_cell_sodium.crypto.algorithm', alias: 'box', is_default: true }

    GeekCell\SodiumBundle\Sodium\Sodium:
        public: true

    GeekCell\SodiumBundle\Command\GenerateKeysCommand:
        tags:
            - { name: 'console.command' }
